Repository interTwin-eu/itwinai, pull requests merged in 2024-10, with the labels that each got.

#222 Distributed print decorator
  pyproject.toml
  src/itwinai/components.py
  src/itwinai/distributed.py
  tests/components/test_decorators.py
Labels: Core prototype⚙️

#226 ADD import sanity checks
  .github/workflows/lint.yml
  .vscode/extensions.json
  src/itwinai/cli.py
  src/itwinai/tests/__init__.py
  src/itwinai/tests/dummy_components.py
  src/itwinai/tests/exceptions.py
  src/itwinai/tests/sanity_check.py
Labels: Core prototype⚙️, dependencies

#219 Usecase eurac
  .github/linters/.flake8
  docs/index.rst
  setup.cfg
  src/itwinai/cli.py
  src/itwinai/loggers.py
  src/itwinai/torch/config.py
  src/itwinai/torch/distributed.py
  src/itwinai/torch/trainer.py
  tutorials/distributed-ml/torch-tutorial-GAN/README.md
  tutorials/distributed-ml/torch-tutorial-GAN/runall.sh
  tutorials/distributed-ml/torch-tutorial-GAN/train.py
  use-cases/eurac/.gitignore
  use-cases/eurac/README.md
  use-cases/eurac/config.yaml
  use-cases/eurac/data.py
  use-cases/eurac/hpo.py
  use-cases/eurac/requirements.txt
  use-cases/eurac/runall.sh
  use-cases/eurac/scaling-test.sh
  use-cases/eurac/slurm.sh
  use-cases/eurac/slurm_ray.sh
  use-cases/eurac/trainer.py
  use-cases/virgo/README.md
  use-cases/virgo/config.yaml
  use-cases/virgo/data.py
  use-cases/virgo/hpo.py
  use-cases/virgo/runall.sh
  use-cases/virgo/scaling-test.sh
  use-cases/virgo/slurm.sh
  use-cases/virgo/slurm_ray.sh
  use-cases/virgo/src/dataset.py
  use-cases/virgo/src/utils.py
  use-cases/virgo/synthetic_data_gen/data_generation.sh
  use-cases/virgo/synthetic_data_gen/file_gen.py
  use-cases/virgo/train.py
  use-cases/virgo/trainer.py
Labels: enhancement

#231 Scalability report update - Communication Plot [cleaned up]
  src/itwinai/cli.py
  src/itwinai/components.py
  src/itwinai/torch/distributed.py
  src/itwinai/torch/profiling/__init__.py
  src/itwinai/torch/profiling/communication_plot.py
  src/itwinai/torch/profiling/profiler.py
  src/itwinai/torch/trainer.py
  use-cases/eurac/config.yaml
  use-cases/eurac/plots/comm_plot.png
  use-cases/eurac/runall.sh
  use-cases/eurac/slurm.sh
  use-cases/eurac/trainer.py
  use-cases/virgo/trainer.py
Labels: enhancement
