Repository interTwin-eu/itwinai, pull requests merged in 2024-12, with the labels that each got.

#261 Add Path in loggers and clearer error handling
  .github/workflows/lint.yml
  .readthedocs.yaml
  src/itwinai/loggers.py
  src/itwinai/parser.py
  src/itwinai/torch/config.py
Labels: enhancement, Core prototype⚙️

#254 Ray torchtrainer integration
  .github/workflows/lint.yml
  pyproject.toml
  src/itwinai/loggers.py
  src/itwinai/torch/distributed.py
  src/itwinai/torch/trainer.py
  src/itwinai/torch/tuning.py
  use-cases/virgo/config.yaml
  use-cases/virgo/hpo.py
  use-cases/virgo/slurm_ray.sh
  use-cases/virgo/trainer.py
Labels: enhancement

#270 HPO tutorial
  .gitignore
  docs/conf.py
  docs/how-it-works/hpo/explain-hpo.rst
  docs/index.rst
  docs/tutorials/hpo-workflows/hpo-workflows.rst
  docs/tutorials/tutorials.rst
  pyproject.toml
  src/itwinai/torch/tuning.py
  tutorials/hpo-workflows/config.yaml
  tutorials/hpo-workflows/data.py
  tutorials/hpo-workflows/slurm_hpo.sh
  tutorials/hpo-workflows/trainer.py
Labels: documentation

#273 Fix tests in container CI
  ci/dagger.json
  env-files/torch/Dockerfile
Labels: bug

#275 sqaaas unit tests failing
  .github/workflows/sqaaas.yml
Labels: bug

#271 Update Virgo README
  use-cases/virgo/README.md
  use-cases/virgo/config.yaml
  use-cases/virgo/trainer.py
Labels: documentation

#276 Add more Search Algorithms and Schedulers for Tuning
  src/itwinai/torch/trainer.py
  src/itwinai/torch/tuning.py
  tutorials/hpo-workflows/config.yaml
  tutorials/hpo-workflows/data.py
  tutorials/hpo-workflows/slurm_hpo.sh
  tutorials/hpo-workflows/trainer.py
  use-cases/virgo/config.yaml
  use-cases/virgo/trainer.py
Labels: enhancement

#265 Slurm script update
  .gitignore
  src/itwinai/loggers.py
  src/itwinai/slurm/slurm.py
  src/itwinai/slurm/slurm_config.yaml
  src/itwinai/slurm/slurm_constants.py
  src/itwinai/slurm/slurm_script_builder.py
  src/itwinai/slurm/utils.py
  tutorials/distributed-ml/torch-scaling-test/slurm.py
  use-cases/eurac/slurm.py
  use-cases/eurac/slurm_config.yaml
  use-cases/eurac/trainer.py
  use-cases/virgo/slurm.py
  use-cases/virgo/slurm_config.yaml
Labels: enhancement
