Repository interTwin-eu/itwinai, pull requests merged in 2024-11, with the labels that each got.

#239 Scalability test wall clock
  .gitignore
  pyproject.toml
  src/itwinai/cli.py
  src/itwinai/loggers.py
  src/itwinai/scalability.py
  src/itwinai/torch/monitoring/monitoring.py
  src/itwinai/torch/monitoring/plotting.py
  src/itwinai/torch/profiling/__init__.py
  src/itwinai/torch/profiling/communication_plot.py
  src/itwinai/torch/profiling/profiler.py
  tutorials/distributed-ml/torch-scaling-test/ddp_trainer.py
  tutorials/distributed-ml/torch-scaling-test/deepspeed_trainer.py
  tutorials/distributed-ml/torch-scaling-test/horovod_trainer.py
  tutorials/distributed-ml/torch-scaling-test/itwinai_trainer.py
  use-cases/eurac/plots/absolute_scalability_plot.png
  use-cases/eurac/plots/communication_plot.png
  use-cases/eurac/plots/gpu_energy_plot.png
  use-cases/eurac/plots/relative_scalability_plot.png
  use-cases/eurac/plots/utilization_plot.png
  use-cases/eurac/trainer.py
  use-cases/virgo/runall.sh
  use-cases/virgo/trainer.py
Labels: enhancement

#236 Itwinai jlab Docker image
  .github/linters/.hadolint.yaml
  .github/workflows/pytest.yml
  README.md
  env-files/tensorflow/Dockerfile
  env-files/tensorflow/create_container_env.sh
  env-files/tensorflow/generic_tf.sh
  env-files/torch/Dockerfile
  env-files/torch/createEnvVega.sh
  env-files/torch/create_container_env.sh
  env-files/torch/generic_torch.sh
  env-files/torch/jupyter/Dockerfile
  env-files/torch/jupyter/README.md
  env-files/torch/jupyter/asyncssh_config.py
  env-files/torch/jupyter/configure.py
  env-files/torch/jupyter/ipython_kernel_config.json
  env-files/torch/jupyter/setup.sh
  env-files/torch/requirements/README.md
  env-files/torch/requirements/cmcc-requirements.txt
  env-files/torch/requirements/requirements.txt
  pyproject.toml
  src/itwinai/cli.py
  src/itwinai/loggers.py
  src/itwinai/torch/distributed.py
  tests/components/test_components.py
  tests/components/test_pipe_parser.py
  tests/components/test_pipeline.py
  tests/conftest.py
  tests/test_loggers.py
  tests/test_utils.py
  tests/torch/conftest.py
  tests/torch/distribtued_decorator.py
  tests/torch/runall.sh
  tests/torch/slurm.vega.sh
  tests/torch/test_config.py
  tests/torch/test_distribtued_training.py
  tests/torch/test_distributed.py
  tests/torch/test_torch_trainer.py
  tests/torch/torch_dist_trainer.py
Labels: Core prototype⚙️

#240 Virgo HDF5 file format
  .github/linters/.ruff.toml
  .github/workflows/lint.yml
  pyproject.toml
  src/itwinai/torch/profiling/profiler.py
  use-cases/eurac/config.yaml
  use-cases/eurac/runall.sh
  use-cases/eurac/slurm.sh
  use-cases/eurac/trainer.py
  use-cases/virgo/config.yaml
  use-cases/virgo/data.py
  use-cases/virgo/hpo.py
  use-cases/virgo/runall.sh
  use-cases/virgo/slurm.sh
  use-cases/virgo/src/dataset.py
  use-cases/virgo/src/model.py
  use-cases/virgo/src/utils.py
  use-cases/virgo/synthetic-data-gen/concat_hdf5_dataset_files.py
  use-cases/virgo/synthetic-data-gen/data_generation_hdf5.sh
  use-cases/virgo/synthetic-data-gen/file_gen_hdf5.py
  use-cases/virgo/synthetic_data_gen/data_generation.sh
  use-cases/virgo/synthetic_data_gen/file_gen.py
  use-cases/virgo/trainer.py
Labels: enhancement

#251 Changed files to create docs env and build docs remotely on juwels
  .gitignore
  .readthedocs.yaml
  docs/README.md
  docs/pre-requirements.txt
  docs/requirements.txt
  env-files/docs/build-docs-jsc.sh
  env-files/docs/create-docs-env-jsc.sh
  pyproject.toml
Labels: bug

#252 Fix scalability bug
  src/itwinai/torch/distributed.py
  src/itwinai/torch/profiling/profiler.py
  use-cases/eurac/config.yaml
  use-cases/eurac/runall.sh
  use-cases/eurac/trainer.py
  use-cases/virgo/trainer.py
Labels: enhancement

#255 Added lightning logger to API reference
  docs/python-api/itwinai.loggers.rst
  docs/python-api/itwinai.torch.modules.rst
Labels: bug

#257 Fix broken docs
  docs/requirements.txt
  pyproject.toml
Labels: bug, documentation

#253 Update docs for use cases with EURAC
  docs/use-cases/3dgan_doc.rst
  docs/use-cases/cyclones_doc.rst
  docs/use-cases/eurac_doc.rst
  docs/use-cases/mnist_doc.rst
  docs/use-cases/use_cases.rst
  docs/use-cases/virgo_doc.rst
Labels: documentation
