Repository interTwin-eu/itwinai, pull requests merged in 2024-07, with the labels that each got.

#181 Add Vega scripts
  Makefile
  env-files/tensorflow/createEnvJSCTF.sh
  env-files/tensorflow/createEnvVegaTF.sh
  env-files/tensorflow/generic_tf.sh
  env-files/torch/createEnvVega.sh
  env-files/torch/generic_torch.sh
  tutorials/distributed-ml/torch-tutorial-2-trainer-class/README.md
  tutorials/distributed-ml/torch-tutorial-2-trainer-class/train.py
Labels: Core prototype⚙️

#183 REFACTOR docs
  docs/README.md
  docs/getting-started/getting_started_with_itwinai.rst
  docs/tutorials/distrib-ml/tf_scaling_test.rst
  docs/tutorials/distrib-ml/tf_tutorial_0_basics.rst
  docs/tutorials/distrib-ml/tf_tutorial_1_imagenet.rst
  docs/tutorials/distrib-ml/torch_scaling_test.rst
  docs/tutorials/distrib-ml/torch_tutorial_0_basics.rst
  docs/tutorials/distrib-ml/torch_tutorial_1_mnist.rst
  docs/use-cases/3dgan_doc.rst
  docs/use-cases/cyclones_doc.rst
  docs/use-cases/mnist_doc.rst
  docs/use-cases/virgo_doc.rst
  use-cases/3dgan/README.md
Labels: documentation

#186 Refactor docs
  .gitignore
  README.md
  docs/how-it-works/training/training.rst
  docs/how-it-works/workflows/figures/simple_pipeline.png
Labels: documentation

#187 Refactor docs
  README.md
  env-files/tensorflow/createEnvJSCTF.sh
  env-files/tensorflow/createEnvVegaTF.sh
  env-files/torch/createEnvJSC.sh
  env-files/torch/createEnvVega.sh
Labels: documentation

#189 Ft update tutorial readme
  tutorials/distributed-ml/torch-tutorial-0-basics/README.md
  tutorials/distributed-ml/torch-tutorial-1-mnist/README.md
Labels: documentation

#190 UPDATE interLink pods for 3DGAN
  use-cases/3dgan/Dockerfile
  use-cases/3dgan/__init__.py
  use-cases/3dgan/config.yaml
  use-cases/3dgan/dataloader.py
  use-cases/3dgan/interLink/3dgan-inference-cpu.yaml
  use-cases/3dgan/interLink/3dgan-inference.yaml
  use-cases/3dgan/interLink/3dgan-train.yaml
  use-cases/3dgan/interLink/README.md
Labels: HPC/Infrastructure 🏭, 🛩️ Use case

#191 Ft gan trainer
  docs/explain_advanced_workflow.rst
  docs/tutorials/distrib-ml/torch-tutorial-GAN.rst
  docs/tutorials/tutorials.rst
  src/itwinai/torch/distributed.py
  src/itwinai/torch/trainer.py
  tutorials/distributed-ml/torch-tutorial-GAN/README.md
  tutorials/distributed-ml/torch-tutorial-GAN/runall.sh
  tutorials/distributed-ml/torch-tutorial-GAN/simpleGAN.py
  tutorials/distributed-ml/torch-tutorial-GAN/slurm.sh
  tutorials/distributed-ml/torch-tutorial-GAN/train.py
Labels: 🛩️ Use case

#178 Prov4ml integration
  pyproject.toml
  src/itwinai/loggers.py
  src/itwinai/torch/trainer.py
  tests/test_loggers.py
  tests/use-cases/test_cyclones.py
  use-cases/3dgan/README.md
  use-cases/3dgan/config.yaml
  use-cases/3dgan/dataloader.py
  use-cases/3dgan/interLink/3dgan-train.yaml
  use-cases/3dgan/model.py
  use-cases/3dgan/run-provenance-experiments.sh
  use-cases/3dgan/slurm.jsc.sh
  use-cases/3dgan/slurm.vega.sh
  use-cases/3dgan/startscript
  use-cases/3dgan/trainer.py
Labels: Core prototype⚙️, 🛩️ Use case

#193 fix gan bug and update docs
  tutorials/distributed-ml/torch-tutorial-0-basics/README.md
  tutorials/distributed-ml/torch-tutorial-GAN/README.md
  tutorials/distributed-ml/torch-tutorial-GAN/train.py
Labels: bug
