Repository interTwin-eu/itwinai, pull requests merged in 2025-03, with the labels that each got.

#337 Migrate to CERN container registry
  .github/actions/build-container/action.yml
Labels: bug

#323 Update SLURM builder
  .gitignore
  Makefile
  docs/getting-started/slurm.rst
  docs/tutorials/distrib-ml/torch-tutorial-GAN.rst
  docs/tutorials/distrib-ml/torch_tutorial_0_basics.rst
  docs/tutorials/distrib-ml/torch_tutorial_1_mnist.rst
  src/itwinai/cli.py
  src/itwinai/slurm/slurm.py
  src/itwinai/slurm/slurm_config.yaml
  src/itwinai/slurm/slurm_constants.py
  src/itwinai/slurm/slurm_script_builder.py
  src/itwinai/slurm/utils.py
  src/itwinai/torch/distributed.py
  src/itwinai/torch/trainer.py
  tests/test_cli.py
  tests/test_slurm_builder.py
  tests/test_utils.py
  tests/use-cases/test_3dgan.py
  tests/use-cases/test_cyclones.py
  tests/use-cases/test_mnist.py
  tutorials/distributed-ml/torch-scaling-test/README.md
  tutorials/distributed-ml/torch-scaling-test/slurm.py
  tutorials/distributed-ml/torch-tutorial-0-basics/README.md
  tutorials/distributed-ml/torch-tutorial-0-basics/runall.sh
  tutorials/distributed-ml/torch-tutorial-0-basics/slurm.sh
  tutorials/distributed-ml/torch-tutorial-0-basics/slurm_config.yaml
  tutorials/distributed-ml/torch-tutorial-1-mnist/.gitignore
  tutorials/distributed-ml/torch-tutorial-1-mnist/README.md
  tutorials/distributed-ml/torch-tutorial-1-mnist/runall.sh
  tutorials/distributed-ml/torch-tutorial-1-mnist/slurm.sh
  tutorials/distributed-ml/torch-tutorial-1-mnist/slurm_config.yaml
  tutorials/distributed-ml/torch-tutorial-GAN/README.md
  tutorials/distributed-ml/torch-tutorial-GAN/runall.sh
  tutorials/distributed-ml/torch-tutorial-GAN/slurm.sh
  tutorials/distributed-ml/torch-tutorial-GAN/slurm_config.yaml
  use-cases/eurac/README.md
  use-cases/eurac/config.yaml
  use-cases/eurac/runall.sh
  use-cases/eurac/scaling-test.sh
  use-cases/eurac/slurm.py
  use-cases/eurac/slurm.sh
  use-cases/eurac/slurm_config.yaml
  use-cases/eurac/trainer.py
  use-cases/mnist/torch-lightning/config.yaml
  use-cases/mnist/torch/runall.sh
  use-cases/mnist/torch/slurm.sh
  use-cases/mnist/torch/slurm_config.yaml
  use-cases/mnist/torch/startscript.sh
  use-cases/virgo/README.md
  use-cases/virgo/config.yaml
  use-cases/virgo/runall.sh
  use-cases/virgo/scaling-test.sh
  use-cases/virgo/slurm.py
  use-cases/virgo/slurm.sh
  use-cases/virgo/slurm_config.yaml
Labels: documentation, enhancement, clean up

#335 Toggle for Profilers
  src/itwinai/loggers.py
  src/itwinai/torch/distributed.py
  src/itwinai/torch/monitoring/monitoring.py
  src/itwinai/torch/profiling/profiler.py
  src/itwinai/torch/trainer.py
  tutorials/distributed-ml/torch-scaling-test/ddp_trainer.py
  tutorials/distributed-ml/torch-scaling-test/deepspeed_trainer.py
  tutorials/distributed-ml/torch-scaling-test/horovod_trainer.py
  tutorials/distributed-ml/torch-scaling-test/itwinai_trainer.py
  use-cases/eurac/config.yaml
  use-cases/eurac/trainer.py
  use-cases/mnist/torch/config.yaml
  use-cases/mnist/torch/slurm.sh
  use-cases/virgo/config.yaml
  use-cases/virgo/trainer.py
Labels: Core prototype⚙️

#353 Functionality for aggregating different runs in the scalability report
  src/itwinai/cli.py
  src/itwinai/scalability_report/data.py
  src/itwinai/scalability_report/reports.py
  src/itwinai/torch/monitoring/monitoring.py
  src/itwinai/torch/profiling/profiler.py
  src/itwinai/torch/trainer.py
  use-cases/virgo/config.yaml
  use-cases/virgo/slurm_config.yaml
  use-cases/virgo/trainer.py
Labels: enhancement
