Repository interTwin-eu/itwinai, pull requests merged in 2025-05, with the labels that each got.

#356 Basic integration with the py-spy profiler
  .github/workflows/lint.yml
  THIRD_PARTY_LICENSES
  licenses/CDDL-1.0.txt
  pyproject.toml
  src/itwinai/cli.py
  src/itwinai/flamegraph.pl
  src/itwinai/slurm/slurm_constants.py
  src/itwinai/slurm/slurm_script_builder.py
  src/itwinai/slurm/utils.py
  src/itwinai/torch/profiling/py_spy_aggregation.py
  use-cases/mnist/torch/config.yaml
  uv.lock
Labels: enhancement

#375 Change itwinai library to general library in data aggregation
  src/itwinai/cli.py
  src/itwinai/torch/profiling/py_spy_aggregation.py
Labels: enhancement

#378 Lumi scripts for MNIST
  use-cases/mnist/torch/runall.jsc.sh
  use-cases/mnist/torch/runall.lumi.sh
  use-cases/mnist/torch/slurm.jsc.sh
  use-cases/mnist/torch/slurm.lumi.sh
Labels: 🛩️ Use case

#382 Fix Radio Astronomy deps
  pyproject.toml
  use-cases/radio-astronomy/requirements.txt
Labels: bug
