Repository interTwin-eu/itwinai, pull requests merged in 2025-01, with the labels that each got.

#285 Lighten logger impact on installation and dynamic import
  env-files/tensorflow/Dockerfile
  env-files/tensorflow/generic_tf.sh
  env-files/torch/Dockerfile
  env-files/torch/generic_torch.sh
  env-files/torch/jupyter/Dockerfile
  env-files/torch/slim.Dockerfile
  pyproject.toml
  src/itwinai/loggers.py
  src/itwinai/torch/distributed.py
  src/itwinai/torch/trainer.py
  tests/loggers/test_lightning_logger.py
  tests/loggers/test_loggers.py
  use-cases/3dgan/trainer.py
  uv.lock
Labels: enhancement, dependencies

#286 Update itwinai user installation and remove itwinai installer
  README.md
  env-files/itwinai-installer.sh
  env-files/tensorflow/Dockerfile
  env-files/tensorflow/generic_tf.sh
  env-files/torch/Dockerfile
  env-files/torch/createEnvVega.sh
  env-files/torch/generic_torch.sh
  env-files/torch/horovod-deepspeed-JSC.slurm
  env-files/torch/jupyter/Dockerfile
  env-files/torch/slim.Dockerfile
  pyproject.toml
  uv.lock
Labels: dependencies

#291 Update building docs
  .github/workflows/build-docs.yml
  .github/workflows/pytest.yml
  docs/Makefile
  docs/README.md
  docs/conf.py
  docs/getting-started/uv-tutorial.md
  docs/how-it-works/training/explain_ddp.rst
  docs/index.rst
  docs/tutorials/distrib-ml/torch_scaling_test.rst
  docs/tutorials/distrib-ml/torch_tutorial_kubeflow_1.rst
  docs/use-cases/cyclones_doc.rst
  docs/use-cases/eurac_doc.rst
  docs/use-cases/use_cases.rst
  docs/use-cases/virgo_doc.rst
  env-files/torch/generic_torch.sh
  src/itwinai/slurm/slurm_script_builder.py
  tutorials/distributed-ml/torch-scaling-test/README.md
  tutorials/ml-workflows/02-pipeline-configuration/tutorial_1_intermediate_workflow.ipynb
  use-cases/eurac/config.yaml
  use-cases/eurac/plots/absolute_scalability_plot.png
  use-cases/eurac/plots/communication_plot.png
  use-cases/eurac/plots/gpu_energy_plot.png
  use-cases/eurac/plots/relative_scalability_plot.png
  use-cases/eurac/plots/utilization_plot.png
  use-cases/eurac/scalability-plots/absolute_scalability_plot.png
  use-cases/eurac/scalability-plots/communication_plot.png
  use-cases/eurac/scalability-plots/gpu_energy_plot.png
  use-cases/eurac/scalability-plots/relative_scalability_plot.png
  use-cases/eurac/scalability-plots/utilization_plot.png
  use-cases/eurac/slurm.py
  use-cases/eurac/slurm_config.yaml
  use-cases/virgo/config.yaml
  use-cases/virgo/data.py
  use-cases/virgo/scalability-plots/absolute_scalability_plot.png
  use-cases/virgo/scalability-plots/communication_plot.png
  use-cases/virgo/scalability-plots/gpu_energy_plot.png
  use-cases/virgo/scalability-plots/relative_scalability_plot.png
  use-cases/virgo/scalability-plots/utilization_plot.png
  use-cases/virgo/slurm.py
  use-cases/virgo/slurm_config.yaml
  use-cases/virgo/trainer.py
Labels: documentation

#305 Fix logger initialization
  .github/workflows/lint.yml
  src/itwinai/loggers.py
  src/itwinai/torch/loggers.py
  tests/loggers/conftest.py
  tests/loggers/test_lightning_logger.py
  tests/loggers/test_loggers.py
  tests/loggers/test_prov4ml.py
Labels: bug, Core prototype⚙️

#306 Fix links in README
  README.md
Labels: bug

#309 Add the possibility to skip logger finalize in lightning logger abstraction
  src/itwinai/torch/loggers.py
Labels: Core prototype⚙️

#238 Update contributors
  AUTHORS.md
  CITATION.cff
  LICENSE
  MAINTAINERS.md
  README.md
  docs/conf.py
  docs/index.rst
Labels: documentation

#302 Unify scalability report
  docs/python-api/itwinai.scalability_report.modules.rst
  docs/python-api/modules.rst
  src/itwinai/cli.py
  src/itwinai/scalability.py
  src/itwinai/scalability_report/data.py
  src/itwinai/scalability_report/plot.py
  src/itwinai/scalability_report/reports.py
  src/itwinai/scalability_report/utils.py
  src/itwinai/tests/sanity_check.py
  src/itwinai/torch/monitoring/plotting.py
  src/itwinai/torch/profiling/communication_plot.py
  use-cases/eurac/.gitignore
Labels: enhancement
