Repository interTwin-eu/itwinai, pull requests merged in 2025-02, with the labels that each got.

#310 Distributed ML Tutorial (presentation)
  docs/tutorials/distrib-ml/torch_tutorial_2_trainer_class.rst
  src/itwinai/cli.py
  src/itwinai/slurm/slurm.py
  tutorials/distributed-ml/torch-tutorial-2-trainer-class/sample_code.py
  tutorials/distributed-ml/torch-tutorial-2-trainer-class/sample_srun.sh
  tutorials/distributed-ml/torch-tutorial-2-trainer-class/slurm_config.yaml
  tutorials/distributed-ml/torch-tutorial-2-trainer-class/train.py
Labels: documentation, enhancement

#282 [DRAFT] Config Parser
  .gitignore
  pyproject.toml
  src/itwinai/cli.py
  src/itwinai/parser.py
  src/itwinai/serialization.py
  src/itwinai/slurm/utils.py
  src/itwinai/utils.py
  tests/components/conftest.py
  tests/components/test_components.py
  tests/components/test_config_parsing.py
  tests/components/test_pipe_parser.py
  tests/components/test_pipeline.py
  tests/test_utils.py
  tests/use-cases/conftest.py
  tests/use-cases/test_3dgan.py
  tests/use-cases/test_cyclones.py
  tests/use-cases/test_mnist.py
  tutorials/distributed-ml/torch-scaling-test/slurm_config.yaml
  tutorials/distributed-ml/torch-tutorial-containers/config.yaml
  tutorials/distributed-ml/torch-tutorial-containers/run_docker.sh
  tutorials/distributed-ml/torch-tutorial-containers/runall.sh
  tutorials/hpo-workflows/distributed-workflow/config.yaml
  tutorials/hpo-workflows/distributed-workflow/slurm_hpo.sh
  tutorials/hpo-workflows/simple-workflow/config.yaml
  tutorials/hpo-workflows/simple-workflow/hpo.py
  tutorials/ml-workflows/02-pipeline-configuration/tutorial_1_intermediate_workflow.ipynb
  use-cases/3dgan/config.yaml
  use-cases/3dgan/run-provenance-experiments.sh
  use-cases/3dgan/slurm.jsc.sh
  use-cases/3dgan/slurm.vega.sh
  use-cases/cyclones/pipeline.yaml
  use-cases/eurac/config.yaml
  use-cases/eurac/hpo.py
  use-cases/eurac/slurm.py
  use-cases/eurac/slurm.sh
  use-cases/eurac/slurm_config.yaml
  use-cases/mnist/tensorflow/pipeline.yaml
  use-cases/mnist/tensorflow/startscript.sh
  use-cases/mnist/torch-lightning/config.yaml
  use-cases/mnist/torch-lightning/startscript
  use-cases/mnist/torch/config.yaml
  use-cases/mnist/torch/runall.sh
  use-cases/mnist/torch/startscript.sh
  use-cases/virgo/config.yaml
  use-cases/virgo/data.py
  use-cases/virgo/hpo.py
  use-cases/virgo/runall.sh
  use-cases/virgo/slurm.py
  use-cases/virgo/slurm_config.yaml
  use-cases/virgo/slurm_ray.sh
  use-cases/xtclim/pipeline.yaml
  use-cases/xtclim/train.py
Labels: enhancement

#328 Parser docs
  docs/tutorials/hpo-workflows/hpo-torchtrainer-integration.rst
  tutorials/ml-workflows/01-pipeline-introduction/basic_components.py
  tutorials/ml-workflows/01-pipeline-introduction/sample_pipeline_2.jpg
  tutorials/ml-workflows/01-pipeline-introduction/tutorial_0_basic_workflow.ipynb
  tutorials/ml-workflows/02-pipeline-configuration/tutorial_1_intermediate_workflow.ipynb
  tutorials/ml-workflows/02-pipeline-configuration/tutorial_1_intermediate_workflow.rst
Labels: documentation
