Repository interTwin-eu/itwinai, pull requests merged in 2025-06, with the labels that each got.

#387 Finalize py-spy integration
  .gitignore
  docs/tutorials/profiling/py-spy-profiling.rst
  docs/tutorials/tutorials.rst
  src/itwinai/cli.py
  src/itwinai/slurm/slurm_script_builder.py
  src/itwinai/slurm/utils.py
  src/itwinai/torch/profiling/profiler.py
  src/itwinai/torch/profiling/py_spy_aggregation.py
  src/itwinai/torch/trainer.py
  tests/test_slurm_builder.py
  use-cases/mnist/torch/slurm_config.yaml
Labels: Clean up, CLI, SLURM

#390 Add documentation for the py-spy profiler
  docs/tutorials/profiling/images/flamegraph.svg
  docs/tutorials/profiling/py-spy-lattice-qcd-example.rst
  docs/tutorials/profiling/py-spy-profiling.rst
  docs/tutorials/tutorials.rst
  src/itwinai/torch/profiling/py_spy_aggregation.py
  use-cases/mnist/torch/config.yaml
Labels: Bug, Documentation

#412 Streamlined docs
  docs/getting-started/getting_started_with_itwinai.rst
  docs/getting-started/slurm.rst
  docs/how-it-works/hpo/explain-hpo.rst
  docs/how-it-works/loggers/explain_loggers.rst
  docs/index.rst
  docs/installation/creating_venv.rst
  docs/installation/developer_installation.rst
  docs/installation/horovod_deepspeed_installation.rst
  docs/installation/hpc_modules.rst
  docs/installation/post_itwinai_installation.rst
  docs/installation/software_prerequisites.rst
  docs/installation/user_installation.rst
  docs/tutorials/tutorials.rst
  docs/use-cases/use_cases.rst
  tutorials/distributed-ml/torch-tutorial-containers/README.md
  tutorials/distributed-ml/torch-tutorial-containers/slurm.sh
  use-cases/3dgan/README.md
  use-cases/3dgan/interLink/3dgan-inference-cpu.yaml
  use-cases/3dgan/interLink/3dgan-inference.yaml
  use-cases/3dgan/interLink/3dgan-train.yaml
  use-cases/eurac/README.md
  use-cases/mnist/tensorflow/README.md
  use-cases/mnist/torch-lightning/README.md
  use-cases/mnist/torch-lightning/startscript
  use-cases/mnist/torch/README.md
  use-cases/virgo/README.md
Labels: Documentation
